# Generated by Django 2.0.1 on 2018-01-26 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collected_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=2000)),
                ('key_positions', models.CharField(blank=True, max_length=4000, null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
                ('cost_time', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('is_labeled', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('settings_id', models.IntegerField(null=True)),
                ('class_list', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='content_group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('settings_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('settings', models.CharField(max_length=500)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('setting_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_single', models.BooleanField(default=False)),
            ],
        ),
    ]
