# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collected_content',
            table='fpm_collected_content',
        ),
        migrations.AlterModelTable(
            name='content',
            table='fpm_content',
        ),
        migrations.AlterModelTable(
            name='content_group',
            table='fpm_content_group',
        ),
        migrations.AlterModelTable(
            name='settings',
            table='fpm_settings',
        ),
    ]
