# Generated by Django 2.0.2 on 2018-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0008_settings_to_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField(null=True)),
                ('accuracy', models.FloatField()),
                ('settings_id', models.IntegerField()),
                ('database', models.CharField(default='', max_length=2000)),
            ],
            options={
                'db_table': 'statistic_info',
            },
        ),
    ]
