# Generated by Django 2.0.2 on 2018-02-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0009_statistic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic_info',
            name='user_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
