# Generated by Django 2.0.2 on 2018-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0011_statistic_info_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_dirty_data',
            field=models.BooleanField(default=False),
        ),
    ]
