# Generated by Django 2.0.2 on 2018-03-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0012_content_is_dirty_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic_info',
            name='accuracy_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='statistic_info',
            name='sum_count',
            field=models.IntegerField(null=True),
        ),
    ]
