# Generated by Django 2.0.2 on 2018-03-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0013_auto_20180320_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='doc_file_path',
            field=models.FileField(help_text='上传的文档', null=True, upload_to='doc_file/%Y-%m-%d/', verbose_name='上传的文档'),
        ),
    ]
