# Generated by Django 2.0.2 on 2018-03-21 05:52

from django.db import migrations, models
import sm_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0014_auto_20180321_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='doc_file_path',
            field=models.FileField(help_text='上传的文档', null=True, upload_to=sm_main.models.upload_to, verbose_name='上传的文档'),
        ),
    ]
