# Generated by Django 2.0.2 on 2018-03-21 06:27

from django.db import migrations, models
import django.utils.timezone
import sm_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0015_auto_20180321_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('last_update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='最后修改日期')),
                ('last_update_user', models.IntegerField(default=0, null=True)),
                ('feedback_question', models.TextField()),
                ('feedback_answer', models.TextField()),
                ('feedback_file_submit', models.FileField(blank=True, help_text='反馈附件', null=True, upload_to=sm_main.models.content_id_submit_path, verbose_name='反馈附件')),
                ('feedback_file_reply', models.FileField(blank=True, help_text='反馈附件', null=True, upload_to=sm_main.models.content_id_reply_path, verbose_name='反馈附件')),
            ],
        ),
    ]
