# Generated by Django 2.0.2 on 2018-03-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm_main', '0016_feedback_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback_content',
            table='fpm_feedback_content',
        ),
    ]
